# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

# Configurations
title: "Galapagos"
author: "9yelin9"
description: "9yelin9's lonely island"

url: "https://9yelin9.github.io"
baseurl: ""
permalink: /:categories/:year-:month-:day-:title:output_ext
  
remote_theme: b2a3e8/jekyll-theme-console
style: dark
listen_for_clients_preferred_style: false
header_pages:
  - index.md
  - about.md

syntax_highlighter_style: colorful
favicon_path: /assets/images/favicon.ico

rss: RSS

plugins:
  - jekyll-seo-tag
