# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

# Configurations
title: "Galapagos"
author: "9yelin9"
description: "9yelin9's lonely island"
remote_theme: b2a3e8/jekyll-theme-console
style: dark
listen_for_clients_preferred_style: false

url: "https://9yelin9.github.io"
baseurl: ""
rss: RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3
  
favicon_path: /assets/images/favicon.ico

# markdown render engine.
markdown: kramdown
kramdown:
  auto_ids:  true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

markdown_ext: markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink: /:categories/:year-:month-:day-:title:output_ext

plugins:
  - jekyll-seo-tag
