# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

# Configurations
title: "Galapagos"
author: "9yelin9"
description: "9yelin9's lonely island"
footer: "Galapagos - 9yelin9's lonely island"
google_analytics: G-9288R0DT8Q

url: "https://9yelin9.github.io"
baseurl: ""
permalink: :permalink
  
remote_theme: b2a3e8/jekyll-theme-console
style: dark
listen_for_clients_preferred_style: false
header_pages:
  - index.md
  - contact.md

syntax_highlighter_style: colorful
favicon_path: /assets/favicon.ico

rss: RSS

plugins:
  - jekyll-seo-tag
